### ISSUE TITLE
Proper way of handling "non unique" unique_key

### ISSUE THREAD

**Issue by asok** [jpmcgrath/shortener#105]
Currently the [code](https://github.com/jpmcgrath/shortener/blob/715b7d981088a08af61f7f1a8d90ae1cf0c5437b/app/models/shortener/shortened_url.rb#L134) for generating an unique key works fine for application that is run in a single thread/process. More on that in this [article](https://robots.thoughtbot.com/the-perils-of-uniqueness-validations).
I think that a better approach would be to just generate a key and attempt to make an insert in a rescue block that would catch any `ActiveRecord::RecordNotUnique`. The block would have to been retried for a newly generated key.
WDYT? Would you accept a PR with such change?

**Comment by jpmcgrath** [comment]
Yes, you are correct that the implementation is not threadsafe. And likewise, ActiveRecord uniqueness validations are not threadsafe and do not protect against race conditions. The solution (as per that linked article) is to enforce the uniqueness inside of the database with an index with a uniqueness constraint. Shortener's migration generator includes such an index:
```
add_index :shortened_urls, :unique_key, unique: true
```
https://github.com/jpmcgrath/shortener/blob/develop/lib/generators/shortener/templates/migration.rb#L28

Does this satisfy your concerns?

I do agree that the logic that you highlighted could be made more robust so has to gracefully handle uniqueness violations at the db level. So yes, we would welcome a PR that ensures the `generate_unique_key` rescues uniqueness violation exceptions raised from the database e.g. `PG::UniqueViolation` for postgres. Note: we'd want to do this in a way that is not locking Shortener to a specific database.

Kind regards.

**Comment by asok** [comment]
In my fork I've implemented [a method](https://github.com/asok/shortener/commit/d6d2a7b04c7eb35f514880bd8d6f3b62a4f8d4b6#diff-2d34f1c6ac3aef84f8d19ed465268c9dR144) that catches this error and retries.
The retries count is 10. I don't know if this the correct number, or should it be allowed to retry infinitely. The latter solution sounded too dangerous to me. WDYT?

**Comment by jpmcgrath** [comment]
I think you are correct to place a limit on the number of retries. I think if there were 10 retries in a row, it would be highly likely that the call is never going to succeed. I am not sure if it is worth it, but we could make it a configurable number.

Your code is a good start, can you include a spec to show fail/retry will find a unique key.
