### ISSUE TITLE
Show short URL from Shortener::ShortenedUrl object

### ISSUE THREAD

**Issue by cseelus** [jpmcgrath/shortener#110]
Is there a method to show the short URL given a `Shortener::ShortenedUrl` object? 

Did not find anything in the code, so currently I'm getting it this way: 
```ruby
shortened_url_object = Shortener::ShortenedUrl.find(foo)
@shortened_url = url_for(controller: :"/shortener/shortened_urls", action: :show, id: shortened_url_object.unique_key, only_path: false)
```

**Comment by jpmcgrath** [comment]
I think that this would be better achieved by your apps routing. e.g.

`get '/:id' => "shortener/shortened_urls#show", as: :shortened`

Then in your views you could do:

`shortened_url(shortened_url_object.unique_key)`

Note: I haven't actually tested the above, but i believe it would work.
