### ISSUE TITLE
Shortener generate failed on rails 3

### ISSUE THREAD

**Issue by jinhucheung** [jpmcgrath/shortener#118]
Hi shortener maintainers,

I installed shortener v0.8.0 on rails 3, and got an error after runing `rails g shortener`

```
/home/jinhu/.rvm/gems/ruby-2.1.9/gems/shortener-0.8.0/app/controllers/shortener/shortened_urls_controller.rb:2:in `<class:ShortenedUrlsController>': uninitialized constant ActionController::StrongParameters (NameError)
	from /home/jinhu/.rvm/gems/ruby-2.1.9/gems/shortener-0.8.0/app/controllers/shortener/shortened_urls_controller.rb:1:in `<top (required)>'
	from /home/jinhu/.rvm/gems/ruby-2.1.9/gems/railties-3.2.22/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
```

ActionController::StrongParameters is not defined on rails 3

How can I solve this error?

Thanks a lot
jimcheung

**Comment by craigmcnamara** [comment]
Rails 3 is out of support.

**Comment by jinhucheung** [comment]
@craigmcnamara thanks fo replying.

Please update the [installation](https://github.com/jpmcgrath/shortener/blob/develop/README.rdoc#installation) for latest readme ?

> Shortener is compatible with Rails v3, v4 & v5

**Comment by winzeler** [comment]
> Shortener is compatible with Rails v3, v4 & v5

Still asserting Rails v3 support in readme.
