### ISSUE TITLE
Faild to add url index faild, it is too long

### ISSUE THREAD

**Issue by jinhucheung** [jpmcgrath/shortener#120]
Hi maintainers,

I installed shortener v0.8.0 on rails 3, run mysql 5.6 (utf8 encoding).

got an error after runing `bundle exec rake db:migrate` for default [migration  file](https://github.com/craigmcnamara/shortener/blob/fixed-length-index-in-migrations/lib/generators/shortener/templates/migration.rb)

```
Mysql2::Error: specified key was too long; max key length is 767 bytes
```

Can shortener delete the url index?

Thanks
JimCheung

**Comment by craigmcnamara** [comment]
The generated migration is a default to get started, you should customize it to fit your needs.

**Comment by jinhucheung** [comment]
@craigmcnamara thanks fo replying.

This index ensures that a record is unique, Deleting it could unlimit length of url and get more compatible.

This index could be replaced by generating a certain key for unique_key index.
