### ISSUE TITLE
Expire after click feature

### ISSUE THREAD

**Issue by sumitdey035** [jpmcgrath/shortener#136]
Hey First of thanks for this beautiful gem.

Is there a way to expire the Shortened Link after it is clicked?

**Comment by fschwahn** [comment]
There's no such feature built-in, but you could expire a link manually by setting `expires_at`, ie. `shortened_url.touch(:expires_at)` should do what you want.

**Comment by jpmcgrath** [comment]
Self destructing links sound like a useful addition, so would be happy to take a PR. I would model it by adding a new column to the db like `expires_after_count`, and the logic would compare that number to the click count.

That said, in reality, these sorts of links might be a bit difficult to share. A lot of email hosts, social networks, and messaging solutions will try and expand a link for the benefit of their users. They do this for a variety of reason such as security, spam detect, or previews. This would either expire the link before the recipient gets to use it, or possibly cache the expanded link in a way that undermines the self-destruction.
