### ISSUE TITLE
Delete Tags to Avoid Confusion

### ISSUE THREAD

**Issue by kyleboe** [jpmcgrath/shortener#145]
The following tags should be deleted from Github to avoid confusion around versioning:
- [4.0.0](https://github.com/jpmcgrath/shortener/releases/tag/v4.0.0)
- [5.0.0](https://github.com/jpmcgrath/shortener/releases/tag/v5.0.0)
- [5.0.1](https://github.com/jpmcgrath/shortener/releases/tag/v5.0.1)

**Comment by fschwahn** [comment]
I removed those obsolete tags. Here are there commits they referenced:

v4.0.0: e654a0f
v5.0.0: 2e56179
v5.0.1: a656dbd
