### ISSUE TITLE
Use browser or crawler_detect gem instead of Voight-Kampff gem

### ISSUE THREAD

**Issue by v-kumar** [jpmcgrath/shortener#151]
This gem uses https://github.com/biola/Voight-Kampff for bot detection. This gem has not been updated in 3 years and is not Ruby 3.0 incompatible. Several PRs and issues have been pending there unaddressed for a long time.

Use the more popular [browser](https://github.com/fnando/browser) or [crawler_detect[(https://github.com/loadkpi/crawler_detect) for the same functionality.

We recently upgraded to ruby 3.0.3, and [File.exists? deprecation warning](https://github.com/biola/Voight-Kampff/pull/49) from kampff gem are flooding the logs.

**Comment by v-kumar** [comment]
Any comments @jpmcgrath ?

**Comment by jpmcgrath** [comment]
Hi there. This seems like a reasonable proposition. I would welcome a pull request (with appropriate specs) to migrate to a better maintained dependency.

**Comment by Blayr** [comment]
@jpmcgrath I've made a PR to upgrade Voight-Kampff to a ruby 3 compatible version (2.0)
https://github.com/jpmcgrath/shortener/pull/158
