### ISSUE TITLE
The link to your shoretner blog post is incorect

### ISSUE THREAD

**Issue by juliancheal** [jpmcgrath/shortener#154]
Hey!

The link on the sidebar of this repo 404's
<img width="327" alt="Screenshot 2022-10-28 at 15 27 54" src="https://user-images.githubusercontent.com/63991/198716985-c92933d5-1fdf-4957-8890-6bf26a9fc2ab.png">
<img width="706" alt="Screenshot 2022-10-28 at 15 28 16" src="https://user-images.githubusercontent.com/63991/198717034-363be84d-f175-4ecd-b5a0-159dc1f8fce8.png">

On your blog however I found this page. https://www.jamespmcgrath.com/projects/shortener/

I'd make a pr, but I don't think that's possible for the repository links.

**Comment by jpmcgrath** [comment]
Thanks, I'll remove that link for now, as the important stuff is covered in the readme.
