### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by v-kumar** [jpmcgrath/shortener#161]
Please release a new version with the latest upgrades to voight_kampff and other fixes.

**Comment by fschwahn** [comment]
@jpmcgrath can you release a new version?

**Comment by mixergtz** [comment]
Please 🙏

**Comment by v-kumar** [comment]
@jpmcgrath Please release a new version or add some of us as contributors so we can act on it please.

**Comment by jpmcgrath** [comment]
@mixergtz @v-kumar @fschwahn version 1.0.1 has just been released.
