### ISSUE TITLE
The gem doesn't seem to work in rails 6.1.7.3

### ISSUE THREAD

**Issue by davidray** [jpmcgrath/shortener#163]
I installed the gem and attempted to follow the instructions to generate the migration:

Could not find generator 'shortener'. 

So I copied the migration from the template and ran that. I got an error on the index size on the url field, but I commented that out and proceeded just to see if I could get the gem to work.

I tried using the "short_url" helper method in an email and got a missing method error.

I think tried to use the Shortener module directly in the console, and it couldn't find the gem.

I haven't had a chance to dig into the reasons, but it appears to me that rails simply can't find the gem, and that's why these features don't work.

**Comment by fschwahn** [comment]
The gem is tested against all rails versions. Also, just tested the generator myself, it works.

Did you add `gem 'shortener'` to your Gemfile? Did you run `bundle install`?

**Comment by davidray** [comment]
I did install the gem, ran bundle install, and restarted rails. But I also have a huge application with hundreds of gems. Maybe there was some weird conflict in my app. At any rate, I just rolled my own - obviously with fewer features, but I didn't need much anyway. I'll close this issue.
