### ISSUE TITLE
retaining the shortcode url

### ISSUE THREAD

**Issue by jnicho02** [jpmcgrath/shortener#164]
My site is login protected. I wish to generate an 'unguessable' url to a hand out to an end customer for them to view their non-login-protected result page (e.g. '/projects/345/results'). As such I don't want them to see the expanded url with the project_id which would enable them to spoof other result page urls.

I figure that I could fetch the url myself, extract the param, and _render_ the view, leaving the url unchanged.  

In 'Logging, stats and other tricks' it states that "you can create your own ‘show` action as follows:". Dumb question, but exactly how do I apply my own show action? Make a copy of app/controllers/shortener/shortened_urls_controller.rb and change my route, or override it, or what?

Or is there a better way? (I could change to using guids for project_ids for one)

**Comment by fschwahn** [comment]
You shouldn't use shortener to secure your result pages. Better approaches could be:
- Adding a token to your projects using `has_secure_token`, and comparing that before showing the result page.
- Switching to UUIDs as you proposed.
- Using signed global_ids (though those may not be URL-safe, not sure)

**Comment by jnicho02** [comment]
Fair enough. The secure token wouldn't be a huge amount of effort to add. Thank you.
