### ISSUE TITLE
Support for non ActiveRecord Interfaces

### ISSUE THREAD

**Issue by adrianmaurer** [jpmcgrath/shortener#18]
Any plans for supporting other interfaces like Mongoid or other persistence like Redis?

**Comment by jpmcgrath** [comment]
@adrianmaurer sorry for the silence. I'd like to add support for other datastores in the future. Now that I have more spare time, it might be something that I can tackle.

Anyone interested in this? If so, what dafastores are of interest? Which data interfaces?

**Comment by BilalReffas** [comment]
Mongo DB would be nice :)
