### ISSUE TITLE
Rails 4 and match

### ISSUE THREAD

**Issue by DaniG2k** [jpmcgrath/shortener#19]
The docs say to add match '/:id' => "shortener/shortened_urls#show" to routes.rb, but this will let the migration fail on Rails 4. It should read "get" instead of "match".

**Comment by NelsonScott** [comment]
Or add 'via: :get' as a param to the match method

**Comment by jpmcgrath** [comment]
Good suggestion @DaniG2k I have replaced match with get in the readme. Cheers.
