### ISSUE TITLE
url that longer than 255

### ISSUE THREAD

**Issue by greatghoul** [jpmcgrath/shortener#31]
by default, shortener support max length 255, but [some urls are much more longer](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

**Comment by jpmcgrath** [comment]
Thanks for point this out @greatghoul This has been addressed in this commit: https://github.com/jpmcgrath/shortener/commit/2e56179d22313e03dd48073392c342cea78d7e14

The url field in the migration file created by the generator is now type text, allowing for much longer urls than 255 chars.
