### ISSUE TITLE
shortened_urls are not correctly associated to a model with ID type == UUID

### ISSUE THREAD

**Issue by oratthumzap** [jpmcgrath/shortener#37]
in our system, we have a model (object) that is defined with an ID field of type UUID.
i created shortened urls with this object as their owner.
even though different instances of this object were used, some URLs were associated with the same owner.
when i looked at the query that was made by the active record i noticed the following:
SELECT COUNT(*) FROM "shortened_urls" WHERE "shortened_urls"."owner_id" = $1 AND "shortened_urls"."owner_type" = $2[0m  [["owner_id", 0], ["owner_type", "Purchase"]]

notice that the owner ID that is used us '0'.

i then also noticed that the DB migration that is created by the gem creates a table with an  'owner' column of type integer.

apparently, this seems to be the issue.

**Comment by jattoabdul** [comment]
Please has this been fixed as I also encountered the same issue.

I have an owner model with id field type UUID and everytime a shortened link is created, the owner_id is set to 0.

How do we resolve this issue?
