### ISSUE TITLE
Set baseurl in config to remove subdomain from the shortened url

### ISSUE THREAD

**Issue by StarWar** [jpmcgrath/shortener#40]
I have my app hosted at www.domain.tld and i want shortened url link to be http://domain.tld/hash , i.e. I don't want subdomain in shortened url. Is there a config option to set base url.

**Comment by jpmcgrath** [comment]
@StarWar apologies for the wait on this. This functionality doesn't currently exist, but I would be interested in including it. I think if we could pass in an options hash to the short_url helper, we can send that option hash through to the url_for method. This would allow you to pass a subdomain, a host, protocol and a number of other settings for the generated url.

Would this meet your original use case?

http://apidock.com/rails/ActionDispatch/Routing/UrlFor/url_for

**Comment by jpmcgrath** [comment]
@StarWar I think this will do the trick: https://github.com/jpmcgrath/shortener/pull/44
