### ISSUE TITLE
How can I set: Shortener.default_redirect = env["REQUEST_URI"]

### ISSUE THREAD

**Issue by zhangliwen** [jpmcgrath/shortener#54]
How can I set: Shortener.default_redirect = env["REQUEST_URI"] if we don't find the shortened link

**Comment by jpmcgrath** [comment]
Not sure that I understand. Is env["REQUEST_URI"] the URI of the shortened url? Are you wanting to NOT redirect if a shortened url is not found?

**Comment by tinavanschelt** [comment]
Didn't post the original question, but that's exactly what I want to do. If there is no shortened url found, I want to go to url specified - not redirect url. What's the best / correct way to do that?

**Comment by salman-haider-confiz** [comment]
any one ?

**Comment by jpmcgrath** [comment]
Sorry for the lag in responding @tinavanschelt, are you after the `Shortener.default_redirect` config option? Checkout the readme and let me know if that suits. Otherwise, I am not clear on the request. Cheers.
