### ISSUE TITLE
Upgrade from v 0.3 to 0.5

### ISSUE THREAD

**Issue by melsatar** [jpmcgrath/shortener#56]
Hi,

I recently updated by ruby from 1.9.3 to 2.1.8

It is safe to upgrade the gem, Shall I change anything in URL generation, I need to keep all the code as it is now? 

Thank you in advance

**Comment by jpmcgrath** [comment]
@melsatar what version of the gem are you on at the moment? The readme discusses required changes needed from migrating from 0.4.1 to more recent versions.
