### ISSUE TITLE
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: unique_key, expires_at

### ISSUE THREAD

**Issue by interpegasus** [jpmcgrath/shortener#62]
Hi,

I would like to know how to fix the following error:

'ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: unique_key, expires_at'

It is for a new installation according to instructions. Thanks

**Comment by interpegasus** [comment]
$ rails console
Shortener::ShortenedUrl.generate("http://example.com")
  Shortener::ShortenedUrl Load (91.0ms)  SELECT "shortened_urls".* FROM "shortened_urls" WHERE "shortened_urls"."url" = 'http://example.com/' LIMIT 1
#<ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: unique_key, expires_at>
 => nil

**Comment by jpmcgrath** [comment]
@interpegasus is this a Rails 3 project? Can you please provide a stacktrace?

**Comment by gitgary** [comment]
I fixed this here: https://github.com/gitgary/shortener and issued a pull request but it never seemed to make it in for some reason.
