### ISSUE TITLE
Using short_url in model

### ISSUE THREAD

**Issue by sengenbe** [jpmcgrath/shortener#66]
I'm attempting to send a tweet containing shortened post_url.  From the view context I can use the short_url method fine but when calling it in the model to prepare the tweet content, it's throwing an error:

```ArgumentError: arguments passed to url_for can't be handled. Please require routes or provide your own implementation```

```
def tweet_url
  old_url = post_url(self)    
  Shortener::ShortenedUrl.generate(old_url) 
  new_url = ApplicationController.helpers.short_url(old_url)
  new_url
end
```
Is there a way to call short_url from a model context?

**Comment by melsatar** [comment]
Yes, how to handle this?

**Comment by simon02** [comment]
Just call `Shortener::ShortenedUrl.generate(old_url) ` again. It will return the `ShortenedUrl` object that was created in the previous `generate`.

Of course in your example you could just do:
```
def tweet_url
  old_url = post_url(self)    
  Shortener::ShortenedUrl.generate(old_url).url # should return the same url everytime you call tweet_url
end
```

**Comment by sengenbe** [comment]
Turned out I was over-complicating it:

def tweet_url
  shortened = Shortener::ShortenedUrl.generate(post_url(self)) 
  shortened.url
end

**Comment by simon02** [comment]
Won't this return `post_url(self)` instead of the shortened url?

**Comment by sengenbe** [comment]
No, the generate method returns a Shortener object which you can just call URL on.

**Comment by simon02** [comment]
Yes, which returns the original URL which has been shortened, not the new &
shortened url which has been created. I thought you needed the latter, not
the former?

**Comment by sengenbe** [comment]
Whoops, I had the old method on my clipboard.  I hacked the url together this way:

`Rails.application.routes.default_url_options[:host]` + "/" + shortened.unique_key
