### ISSUE TITLE
How to defend against Open Redirect Vulnerability?

### ISSUE THREAD

**Issue by cberkom** [jpmcgrath/shortener#67]
Do you have any recommendations on how to defend against [open-redirects](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet)?

I'm thinking either:
- using user scopes, and authenticating against logged-in users
- displaying a confirmation page before redirecting, which cannot be circumvented with url parameters

**Comment by craigmcnamara** [comment]
You could not allow users control of redirects from your app, or use a solution like https://github.com/kickstarter/rack-attack to throttle or block certain traffic.

**Comment by jpmcgrath** [comment]
@cberkom If I understand the "open redirect" vulnerability correctly, it involves tricking a user into visiting unsafe URLs, by hiding them inside a safe looking url.

e.g. `http://example.com/example.php?url=http://malicious.example.com`

Are you allowing people to generate their own shortened urls? If so, it will be difficult to control this sort of attack, beyond your second suggestion of a confirmation page.

I can see that Shortener's feature of passing on [url params to the destination url](https://github.com/jpmcgrath/shortener#url-parameters) could be used in abusive ways. I would be open to a pull requests that adds a configuration option to disable this feature. If you do want such a feature, please include specs to cover default off and turned on behavior.

Cheers.
