### ISSUE TITLE
migration: MySQL requires index length to be specified for column `url`

### ISSUE THREAD

**Issue by TristeFigure** [jpmcgrath/shortener#70]
This is the error I get when I run
`rake db:migrate`
after having run
`rails generate shortener`

> ==  CreateShortenedUrlsTable: migrating =======================================
> -- create_table(:shortened_urls)
>    -> 0.0236s
> -- add_index(:shortened_urls, :unique_key, {:unique=>true})
>    -> 0.0164s
> -- add_index(:shortened_urls, :url)
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> **Mysql2::Error: BLOB/TEXT column 'url' used in key specification without a key length: CREATE  INDEX `index_shortened_urls_on_url` ON `shortened_urls` (`url`)**
> /.../db/migrate/20160422152339_create_shortened_urls_table.rb:26:in `change'
> ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'url' used in key specification without a key length: CREATE  INDEX `index_shortened_urls_on_url` ON `shortened_urls` (`url`)
> /.../db/migrate/20160422152339_create_shortened_urls_table.rb:26:in `change'
> Mysql2::Error: BLOB/TEXT column 'url' used in key specification without a key length
> /.../db/migrate/20160422152339_create_shortened_urls_table.rb:26:in `change'
> Tasks: TOP => db:migrate
> (See full trace by running task with --trace)

This is easily corrected by replacing `shortener/lib/generators/shortener/templates/migration.rb`, [line 26](https://github.com/jpmcgrath/shortener/blob/develop/lib/generators/shortener/templates/migration.rb#L26) (or the generated migration file) with

``` ruby
    add_index :shortened_urls, :url, :length => { :url => 5 }
```

I'm using `mysql  Ver 14.14 Distrib 5.6.29, for osx10.8 (x86_64) using  EditLine wrapper`.
MySQL only index the N first characters of `TEXT` or `BLOB` columns, and requires this index length to be specified. See: [MySQL error: key specification without a key length on Stackoverflow](http://stackoverflow.com/a/1827099).
I don't think the specific index length I used is pertinent, all the more so I only shorten URLs from my own domain, which is longer than 5 characters...
How frequently is this specific index used ? Could I remove it ?

**Comment by conradchu** [comment]
+1

**Comment by morais17** [comment]
Had this problem too

**Comment by craigmcnamara** [comment]
Fixed in https://github.com/jpmcgrath/shortener/pull/93
