### ISSUE TITLE
Consider providing migrations

### ISSUE THREAD

**Issue by mvz** [jpmcgrath/shortener#78]
Rails engines have the ability to provide migrations, so that on upgrade the user can obtain the latest migrations simply by invoking:

```bash
bundle exec rake shortener:install:migrations
```

Please consider providing such migrations instead of only listing them in the README.

**Comment by craigmcnamara** [comment]
Migrations are provided by the generator as noted in the readme. There is a discussion here https://github.com/jpmcgrath/shortener/issues/70 regarding this known issue.

I think this ticket can be considered closed.

**Comment by mvz** [comment]
No, that migration is the initial migration. I'm talking about the migrations listed in [the Upgrading section](https://github.com/jpmcgrath/shortener#upgrading).
