### ISSUE TITLE
prevent certain characters from be generating into url?

### ISSUE THREAD

**Issue by chenjau** [jpmcgrath/shortener#82]
for example: 0 o i 1 l I, is that possible? thanks.

**Comment by jpmcgrath** [comment]
@chenjau Right now this is not possible out of the box. We'd have to add the ability to supply a set of characters in the configuration, or add a non-abiguous charset here:
https://github.com/jpmcgrath/shortener/blob/develop/lib/shortener.rb#L8-L11

A PR with specs would be welcome!

Cheers.
