### ISSUE TITLE
owner_type > 20 chars

### ISSUE THREAD

**Issue by oaguy1** [jpmcgrath/shortener#90]
Hello! 

I am running into an issue where the classname of the model that owns a shortened url (via ```has_shortened_urls```) is over 20 characters long and therefore not able to be stored in shortedned_urls table as it is generated by the gem. Is there was a reason the owner_type is limited to 20 chars and will increasing it cause any harm in a production system? I am happy to modify this behavior in my rails project, but before to check in.

Thanks in advance and love the gem!

**Comment by jpmcgrath** [comment]
@oaguy1 I imagine that that this limitation was introduced to make indexing more efficient. Feel free to remove that limitation if it fits your purposes.
